name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: List directory structure
#        run: |
#          echo "Root directory:"
#          ls -la
#          echo "\nFind all .sln files:"
#          find . -name "*.sln"
#          echo "\nFind all .csproj files:"
#          find . -name "*.csproj"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./SoftLudo/SoftLudo.sln

      - name: Build
        run: dotnet build ./SoftLudo/SoftLudo.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./SoftLudo/SoftLudo.sln --no-build --verbosity normal --logger "console;verbosity=detailed"