name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SOFTludo/Softludo/SoftludoAPI/SoftludoAPI.csproj

      - name: Build
        run: dotnet build SOFTludo/Softludo/SoftludoAPI/SoftludoAPI.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test SOFTludo/Softludo/SoftludoAPI/SoftludoAPI.csproj --no-build --verbosity normal --logger "console;verbosity=detailed"